POST https://lv.blumbit.net/back/public/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
    "email": "admin@mail.com",
    "password": "admin54321"
}

### Recuperar Categorias
GET https://lv.blumbit.net/back/public/api/categoria
Accept: application/json
Content-Type: application/json
Authorization: Bearer 69|M3X4Dwf3cCy1jASSkVDr723FZjFKmBlq4WM0dAMP7019c05d

### Recuperar Categoria
GET https://lv.blumbit.net/back/public/api/categoria/2
Accept: application/json
Content-Type: application/json
Authorization: Bearer 62|z0Qa111N3Zb1kCJGLkoSXdIcIpiK8YvTRPZrjoAtc04fb8cd
